version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Develeb-Platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Develeb-Platform
      DB_USER: user
      DB_PASSWORD: changemeinprod!
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

volumes:
  postgres_data: